### ISSUE TITLE
Provide a Denite source

### ISSUE THREAD

**Issue by languitar** [urbainvaes/vim-remembrall#13]
Would it be possible to provide a Denite source for this plugin instead of a custom selection UI?

**Comment by urbainvaes** [comment]
I think someone mentioned that there was already one for Unite, so I
suppose that there should be one for denite too? It's certainly
possible.

**Comment by languitar** [comment]
Sources are different at least. I know that there is a command source for Denite, but I couldn't find one for mappings.

**Comment by urbainvaes** [comment]
Indeed, it looks like there isn't one; adding it would probably not be too difficult, though, given that the `:map` command to list all mappings... 

This plugin is pretty much only about the custom selection UI, so I'll close this issue.
