### ISSUE TITLE
Breaks copy / delete to registers

### ISSUE THREAD

**Issue by urbainvaes** [urbainvaes/vim-remembrall#3]

**Comment by fearphage** [comment]
I'm having this problem as well. How'd you fix this?

**Comment by urbainvaes** [comment]
Thanks for reporting this. I made a change a couple of days ago to try to fix this problem in most cases - have you tried pulling the latest version? If your specific problem persists, could you tell me how to reproduce it?

**Comment by fearphage** [comment]
@urbainvaes I just pulled the latest updates. Things like `10dd` and `3yy` aren't working for me with the plugin installed.

**Comment by urbainvaes** [comment]
Ah, that's annoying, I hadn't realised. I do not have access to a laptop until tonight, but I'll look at the issue when I get home. 

Does vim simply lose the count and act on the current line, or do other problems happen? In the former case, it might be possible to fix the problem by adding `v:count` (if that variable exists) to the `feedkeys` function.

In the meantime, I suggests that you remove the c, y, and d keys from `g:remembrall_normal_keys`. In fact, I was thinking of removing them from the default list, as they are more likely to break things than the rest.

Thanks again for reporting this.

**Comment by fearphage** [comment]
Delete deletes the wrong lines and yank moves the cursor and I didn't check to see if the yank worked correctly.

For anyone looking for a copy-paste temporary fix, the following lets me use vim normally again:

```vimrc
 let g:remembrall_normal_keys = ["]", "[", ">", "<", "="]
```

**Comment by urbainvaes** [comment]
Thanks for the feedback. Does the problem happen even without a count. If yes, could you give details that would allow reproducing the problem?

**Comment by fearphage** [comment]
No, `dd` and `dw` work just fine. Using either of them with a number is where the problem lies.

This doesn't apply to some of the other keys. I had three files opened in a vertical split with my cursor in the rightmost file. I tried to un-indent a line `<<` and it ended up switching to the middle file and un-indenting a line there. None of the other commands jumped to other files. That's the only one I tried several times before disabling it.

**Comment by urbainvaes** [comment]
Hi!

Finally got back home.

- The cursor moving to a different window is another issue that I hadn't experienced - it should be fixed by commit https://github.com/urbainvaes/vim-remembrall/commit/c12bfabd5db262316427af1d60f6fcf2165dc424.

- The problem with counts should also be resolved, by https://github.com/urbainvaes/vim-remembrall/commit/dff82e372bc49af51e34f6f6b5b510323ff4e12c. The workaround I used feels like a bit of a hack, so I'll think of a better solution this weekend. I think that, in this case, using`nnoremap <expr>` might be better than using `feedkeys`.

Anyway, thanks for taking the time to report the bugs before giving up.

**Comment by fearphage** [comment]
Yeah, everything I've tried seems to work. Thanks for the quick fixes!
